name: voute
description: Voute.
version: 0.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6
  rxdart: ^0.22.0
  shared_preferences: ^0.5.3
  flutter_spinkit: ^3.0.0
  get_version: ^0.1.0
  version: ^1.0.0
  equatable: ^0.2.6
  rebloc: ^0.2.0
  http_middleware:
    git:
      url: https://github.com/jogboms/http_middleware.git
  http_logger:
    git:
      url: https://github.com/jogboms/http_logger.git
  provider: ^3.0.0
  injector: ^1.0.6
  built_value: ^6.4.0
  built_collection: ^4.2.0
  url_launcher: ^5.0.3
  # TODO: blocked by https://github.com/benhurott/flutter-masked-text/pull/32/
  # flutter_masked_text: ^0.8.0
  flutter_masked_text:
    git:
      url: https://github.com/jogboms/flutter-masked-text.git
  overlay_support: ^0.3.0
  share: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mfsao: ^0.1.3
  build_runner: ^1.3.1
  built_value_generator: ^6.4.0

flutter:
  uses-material-design: true
  # assets:
  # - assets/images/
  # fonts:
  #   - family: Open Sans
  #     fonts:
  #       - asset: assets/fonts/OpenSans-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/OpenSans-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/OpenSans-Semibold.ttf
  #         weight: 500
  #       - asset: assets/fonts/OpenSans-Bold.ttf
  #         weight: 600
