name: voute
description: Voute.
version: 0.1.0

environment:
  sdk: ">=2.6.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  rxdart: ^0.22.5
  shared_preferences: ^0.5.4+3
  flutter_spinkit: ^4.0.0
  get_version: ^0.2.0+1
  equatable: ^0.6.1
  rebloc: ^0.3.0+1
  http_middleware:
    git:
      url: https://github.com/jogboms/http_middleware.git
  http_logger:
    git:
      url: https://github.com/jogboms/http_logger.git
  provider: ^3.1.0+1
  injector: ^1.0.8
  built_value: ^6.3.0
  built_collection: ^4.2.2
  overlay_support: ^1.0.2
  lumberdash: ^2.1.0
  colorize_lumberdash: ^2.1.0
  flutter_swiper: ^1.1.6
  after_layout: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mfsao: ^0.1.3
  build_runner: ^1.7.2
  built_value_generator: ^6.4.0
  flutter_launcher_icons: ^0.7.4
  feather_icons_flutter: ^4.7.4

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/ic_launcher.png"
  adaptive_icon_background: "assets/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/ic_launcher_transparent.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OCR A Std
      fonts:
        - asset: assets/fonts/OCR A Std Regular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 900
