const String PERSISTED_LOGIN_EMAIL = "PERSISTED_LOGIN_EMAIL";
const String PERSISTED_ID_TOKEN = "PERSISTED_ID_TOKEN";
const String IS_FIRST_TIME = "IS_FIRST_TIME";
const String IS_FIRST_TIME_LOGIN = "IS_FIRST_TIME_LOGIN";
const String FCM_DEVICE_TOKEN = "FCM_DEVICE_TOKEN";
const int MAX_FETCH_LIMIT = 20;
